# Generated by Django 4.0.6 on 2022-08-01 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartName',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_type', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
    ]
