# Generated by Django 4.0.6 on 2022-08-01 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_chartsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='chartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_data', models.TextField()),
                ('chart_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.chartname')),
            ],
        ),
    ]
