# Generated by Django 4.0.6 on 2022-08-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_chartdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.IntegerField(blank=True, null=True)),
                ('sepal_width', models.IntegerField(blank=True, null=True)),
                ('petal_length', models.IntegerField(blank=True, null=True)),
                ('petal_width', models.IntegerField(blank=True, null=True)),
                ('varity', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chartsheet',
            name='chart_sub_title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chartsheet',
            name='chart_title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chartsheet',
            name='labels',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chartsheet',
            name='number_suffix',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chartsheet',
            name='values',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chartsheet',
            name='x_axis_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chartsheet',
            name='y_axis_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
