# Generated by Django 4.0.6 on 2022-08-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_data_alter_chartsheet_chart_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='data',
        ),
    ]
