# Generated by Django 4.0.6 on 2022-08-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_remove_chartdata_chart_sheet_alter_chartdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='chart_name',
            field=models.CharField(blank=True, db_column='chart_name', db_index=True, max_length=255, null=True),
        ),
    ]
