# Generated by Django 4.0.6 on 2022-08-02 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_chartdata_chart_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dashboard_name', models.CharField(blank=True, db_column='chart_name', db_index=True, max_length=255, null=True)),
                ('dashboard_data', models.TextField()),
            ],
        ),
    ]
