# Generated by Django 4.0.6 on 2022-08-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_alter_chartdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboard',
            table='dashboarddata',
        ),
    ]
