# Generated by Django 4.0.6 on 2022-08-16 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_alter_dashboard_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='chart_query',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
