# Generated by Django 4.1 on 2022-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0016_dashboard_filter_dashboard_data_dashboard_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartdata",
            name="filter_script_data",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chartdata",
            name="javascript_script",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
