# Generated by Django 4.1 on 2022-12-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0017_chartdata_filter_script_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartdata",
            name="chart_unique_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
